services:
  postgres:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vini
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=suricato
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: