# fly.toml app configuration file generated for contai-backend on 2025-06-10T00:51:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contai-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
